services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8080:8080"

  kafka-init:
    container_name: kafka-init
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - kafka
    entrypoint: |
      bash -c "
      sleep 15;
      kafka-topics --create --if-not-exists --topic messages --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092;
      kafka-topics --create --if-not-exists --topic filtered_messages --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092;
      kafka-topics --create --if-not-exists --topic blocked_users --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092;
      kafka-topics --create --if-not-exists --topic censored_words --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092;
      "

  app:
    container_name: lab3-app
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      kafka-init:
        condition: service_completed_successfully
